# Generated by Django 4.0.5 on 2022-06-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'iso',
            },
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.FloatField()),
                ('south', models.FloatField()),
                ('east', models.FloatField()),
                ('west', models.FloatField()),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.iso')),
            ],
            options={
                'db_table': 'map_point',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.TextField()),
                ('language_of', models.TextField()),
                ('alternate_names', models.TextField()),
                ('autonym', models.TextField()),
                ('user_population', models.TextField()),
                ('location', models.TextField()),
                ('language_maps', models.TextField()),
                ('language_status', models.TextField()),
                ('classification', models.TextField()),
                ('dialects', models.TextField()),
                ('typology', models.TextField()),
                ('language_use', models.TextField()),
                ('language_development', models.TextField()),
                ('language_resource', models.TextField()),
                ('writing', models.TextField()),
                ('other_comments', models.TextField()),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.iso')),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
